version: "3"
services:
    client:
        container_name: client
        build: ./client
        restart: always
        command: npm run start
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - backend
        depends_on:
          - backend
    backend:
        container_name: backend
        build: ./backend
        restart: always
        command: npm run start
        ports:
            - "4000:4000"
        # volumes:
        #     - ./:/backend
        #     - /backend/node_modules
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
       
        # expose:
        #      - "28017"
        restart: always
        # volumes:
        #     - mongodata:/data/db
        ports:
            - "28017:27017"
volumes:
    mongodata:
