---
# Setup LAMP Stack
- hosts: localhost
  connection: local
  tasks:
    - name: stop apache service
      become: yes
      become_user: root
      service:
          name: apache2
          state: stopped


    - name: uninstall lamp stack
      become: yes
      become_user: root
      apt:
        pkg:
          - apache2
          - mysql-server
          - php7.4
        autoremove: yes
        state: absent
